service: socket
frameworkVersion: '>=2.0.0'
variablesResolutionMode: 20210326
projectDir: ../..

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}

functions:
  websocket:
    handler: src/handler.socket
    events:
      - websocket:
          route: $connect

      - websocket:
          route: ping

      - websocket:
          route: $default

      - websocket:
          route: $disconnect

plugins:
  - serverless-bundle
  - serverless-offline
