service: auth
frameworkVersion: '>=2.0.0'
variablesResolutionMode: 20210326
projectDir: ../..

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}

#   environment:
#     MONGO_CONN: ${self.custom.mongoConn.${self:provider.stage}}

# custom:
#   stages:
#     - dev
#     - production
#   mongoConn:
#     dev: ${env:MONGO_CONN}
#     production: ${ssm:/app/production/mongo-conn}

functions:
  hello:
    handler: src/handler.ping
    events:
      - httpApi:
          path: /ping
          method: get

plugins:
  - serverless-bundle
  - serverless-offline
