service: auth
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.ping
    events:
      - httpApi:
          path: /ping
          method: get

plugins:
  - serverless-offline
